### ISSUE TITLE
garbage_collect_files works only on second try

### ISSUE THREAD

**Issue by kkonevets** [quickwit-oss/tantivy#552] opened 2019-05-23 16:35 UTC
**Describe the bug**
the snippet code I use is [here](https://github.com/tantivy-search/tantivy/issues/510#issuecomment-495099648) 

`garbage_collect_files` does not work the first time I use it, only the second time.
First time means first call of `garbage_collect_files` in one thread, second means second call of `garbage_collect_files` in another thread

**Which version of tantivy are you using?**
0.9.1

**To Reproduce**

 [repo](https://github.com/kkonevets/tsearch) where is all the code I used, look at `drop_index()` function in src/bin/server.rs

I use POST request to trigger `garbage_collect_files` like this:
`POST http://localhost:8080/drop`

When I post at first time all documents are deleted but `./index` directory does not become empty, actually it has 36Mb data in it. Original size of index directory was 129Mb
When I post at second time directory size drops to 8,0K. Nothing else but second call to `garbage_collect_files` happens.

I don't know, maybe it is an expected behavior, but is weird.

**Comment by fulmicoton** [comment] 2019-05-29 00:35
There can be multiple reasons why files do not get deleted on your first call :
a merging thread was still running, merging two obsolete segment. It's job would then get discarded when it finished.
If you are on Windows, it can also happen that you had a reader open and it prevented tantivy from removing the files.

This is not a bug as is... But I have an extra question.
If you did not call `drop` the second time but just waited 1mn. Are your files deleted automatically ?
If not I think this is ok to consider this a bug.

**Comment by fulmicoton** [comment] 2019-05-29 00:36
(also sorry for the late answer.)

**Comment by kkonevets** [comment] 2019-05-29 04:39
I am on Mac OS. Same problem on Ubuntu.
I have waited for 5 minutes after first drop, no thread running - `index` directory is still 32Mb. Again, after second `drop` index becomes 8Kb

**Comment by fulmicoton** [comment] 2019-06-08 22:46
Does someone have bandwidth to create a branch and create a unit test to reproduce?

"do a (.add_document()s, .commit()s) sequence that triggers it", index.wait_merge_threads, and check for the number of documents in the directory.

Do a gc, and see if this number decrease. (if so this is a bug. GC should not be required.)

**Comment by fulmicoton** [comment] 2019-06-16 04:24
I think I found the problem. The fix is on the way.

@kkonevets 
Could you confirm that the problem is fixed when you depend on master once the branch is merged,
and comment on this ticket and possibly reopen it if you can still reproduce.

**Comment by kkonevets** [comment] 2019-06-16 06:40
Nope, it does not work. Actually it became worse. Now index size increased after first call. Later it was 36Mb now it is 87Mb. Initial size was 140Mb.
I did not change my code and data.

**Comment by kkonevets** [comment] 2019-06-16 06:41
If you wish I can give you the data and you can try on your own.

**Comment by fulmicoton** [comment] 2019-06-16 07:25
im interested yes @kkovenets

**Comment by kkonevets** [comment] 2019-06-16 07:54
To reproduce:

0) my source code https://github.com/kkonevets/tsearch
1) download the database https://yadi.sk/d/-k357Cgo-vFQlw
2) Install MySQL server (I use `brew install mysql`) and optionally this client https://dev.mysql.com/downloads/workbench/  (I am on Mac OS)
3) create new schema and name it `ssergeev`
![2019-06-16_10-37-14](https://user-images.githubusercontent.com/16817116/59560975-d9ddf280-9022-11e9-9805-c150351d61e9.png)
4) `Server->Data Import` and `Import from self-Contained file`, choose the file I gave you with extension `.sql`
5) In cargo.toml set dependency on master as you said:
`
tantivy = { git = "https://github.com/tantivy-search/tantivy" }
`
6) create index `cargo run --release --bin commit`
7) start the server `cargo run --release --bin server`
8) I use [this](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) extension for VS Code to test REST API, install it
Then open `test.http` file in the src directory and press `Send Request` button:
![2019-06-16_10-51-34](https://user-images.githubusercontent.com/16817116/59561117-db101f00-9024-11e9-9d91-1547ad96863a.png)
This will call `garbage_collect_files()` once.

**Comment by fulmicoton** [comment] 2019-06-17 01:00
These are very thorough instructions... but I unfortunately don't have time to install Microsoft SQL Server :-S

**Comment by fulmicoton** [comment] 2019-06-17 01:16
The problem looks fixed on my computer. 

I'm sorry to ask something like that but can you double check?

- Fix the revision of tantivy to something specific (e.g.: c23a7c992bcf0f9b052995941fdfe1f3e87e3d53)
- Index your files without calling your manual garbage collect. Ideally, run your program with the  `RUST_LOG=info` command and *send me the logs*.
- Commit.
- Wait for 5 minutes. (it is normal for files to appear and disappear after a commit. Tantivy merges segment together. This should appear in the logs.)
- Send me the list of files in your directory.
- Send me the `meta.json` at this point.
- Trigger your garbage_collect  
- Confirm that some file got deleted.

**Comment by kkonevets** [comment] 2019-06-17 05:18
What do you mean by commit? In my terminology commit is actually indexing. 

Anyway, here is the remaining files after first garbage collect:
4,0K    index/79b9e51a42a34d63bd7690104f8c02dd.fast                                            
292K    index/79b9e51a42a34d63bd7690104f8c02dd.fieldnorm                                       
 11M    index/79b9e51a42a34d63bd7690104f8c02dd.idx                                             
 11M    index/79b9e51a42a34d63bd7690104f8c02dd.pos                                            
 64K    index/79b9e51a42a34d63bd7690104f8c02dd.posidx                                          
4,0M    index/79b9e51a42a34d63bd7690104f8c02dd.store                                           
5,3M    index/79b9e51a42a34d63bd7690104f8c02dd.term                                            
4,0K    index/meta.json                                                                        

meta.json after first garbage collect:

{
  "segments": [],
  "schema": [
    {
      "name": "thread_id",
      "type": "i64",
      "options": {
        "indexed": true,
        "stored": true
      }
    },
    {
      "name": "title",
      "type": "text",
      "options": {
        "indexing": {
          "record": "position",
          "tokenizer": "ru_stem"
        },
        "stored": true
      }
    },
    {
      "name": "text",
      "type": "text",
      "options": {
        "indexing": {
          "record": "position",
          "tokenizer": "ru_stem"
        },
        "stored": false
      }
    },
    {
      "name": "node_id",
      "type": "i64",
      "options": {
        "indexed": true,
        "stored": false
      }
    },
    {
      "name": "needModer",
      "type": "i64",
      "options": {
        "indexed": true,
        "stored": false
      }
    },
    {
      "name": "post_date",
      "type": "i64",
      "options": {
        "indexed": true,
        "stored": false
      }
    }
  ],
  "opstamp": 303218
}


This is after the second garbage collect:
4,0K    index/meta.json

**Comment by kkonevets** [comment] 2019-06-17 05:28
List of files after commit:

01f9473202474d2bab75d0d6271f1b59.fast
01f9473202474d2bab75d0d6271f1b59.fieldnorm
01f9473202474d2bab75d0d6271f1b59.idx
01f9473202474d2bab75d0d6271f1b59.pos
01f9473202474d2bab75d0d6271f1b59.posidx
01f9473202474d2bab75d0d6271f1b59.store
01f9473202474d2bab75d0d6271f1b59.term
022e975a61eb4a649d010d31d1afe322.fast
022e975a61eb4a649d010d31d1afe322.fieldnorm
022e975a61eb4a649d010d31d1afe322.idx
022e975a61eb4a649d010d31d1afe322.pos
022e975a61eb4a649d010d31d1afe322.posidx
022e975a61eb4a649d010d31d1afe322.store
022e975a61eb4a649d010d31d1afe322.term
03d40ce6be4f4b84ace29c82b979a3a4.fast
03d40ce6be4f4b84ace29c82b979a3a4.fieldnorm
03d40ce6be4f4b84ace29c82b979a3a4.idx
03d40ce6be4f4b84ace29c82b979a3a4.pos
03d40ce6be4f4b84ace29c82b979a3a4.posidx
03d40ce6be4f4b84ace29c82b979a3a4.store
03d40ce6be4f4b84ace29c82b979a3a4.term
080c5b4bd3c64d3687aa0f27e7d1af45.fast
080c5b4bd3c64d3687aa0f27e7d1af45.fieldnorm
080c5b4bd3c64d3687aa0f27e7d1af45.idx
080c5b4bd3c64d3687aa0f27e7d1af45.pos
080c5b4bd3c64d3687aa0f27e7d1af45.posidx
080c5b4bd3c64d3687aa0f27e7d1af45.store
080c5b4bd3c64d3687aa0f27e7d1af45.term
0aca54b72f7a4abaaf2d6fa947009a8c.fast
0aca54b72f7a4abaaf2d6fa947009a8c.fieldnorm
0aca54b72f7a4abaaf2d6fa947009a8c.idx
0aca54b72f7a4abaaf2d6fa947009a8c.pos
0aca54b72f7a4abaaf2d6fa947009a8c.posidx
0aca54b72f7a4abaaf2d6fa947009a8c.store
0aca54b72f7a4abaaf2d6fa947009a8c.term
123489efac2c4204a856fb44b1cc0c63.fast
123489efac2c4204a856fb44b1cc0c63.fieldnorm
123489efac2c4204a856fb44b1cc0c63.idx
123489efac2c4204a856fb44b1cc0c63.pos
123489efac2c4204a856fb44b1cc0c63.posidx
123489efac2c4204a856fb44b1cc0c63.store
123489efac2c4204a856fb44b1cc0c63.term
22e58d87d9cb4eabbc22b7cf8e5ccc29.fast
22e58d87d9cb4eabbc22b7cf8e5ccc29.fieldnorm
22e58d87d9cb4eabbc22b7cf8e5ccc29.idx
22e58d87d9cb4eabbc22b7cf8e5ccc29.pos
22e58d87d9cb4eabbc22b7cf8e5ccc29.posidx
22e58d87d9cb4eabbc22b7cf8e5ccc29.store
22e58d87d9cb4eabbc22b7cf8e5ccc29.term
2399db47307e4741b8825c10cb9b1587.fast
2399db47307e4741b8825c10cb9b1587.fieldnorm
2399db47307e4741b8825c10cb9b1587.idx
2399db47307e4741b8825c10cb9b1587.pos
2399db47307e4741b8825c10cb9b1587.posidx
2399db47307e4741b8825c10cb9b1587.store
2399db47307e4741b8825c10cb9b1587.term
3b57082dd7164be99717762d61a3dbf9.fast
3b57082dd7164be99717762d61a3dbf9.fieldnorm
3b57082dd7164be99717762d61a3dbf9.idx
3b57082dd7164be99717762d61a3dbf9.pos
3b57082dd7164be99717762d61a3dbf9.posidx
3b57082dd7164be99717762d61a3dbf9.store
3b57082dd7164be99717762d61a3dbf9.term
3ef65b1c11954fe38df84cfeea413cb0.fast
3ef65b1c11954fe38df84cfeea413cb0.fieldnorm
3ef65b1c11954fe38df84cfeea413cb0.idx
3ef65b1c11954fe38df84cfeea413cb0.pos
3ef65b1c11954fe38df84cfeea413cb0.posidx
3ef65b1c11954fe38df84cfeea413cb0.store
3ef65b1c11954fe38df84cfeea413cb0.term
46d1c36833fd46ca88622272b3a12b72.fast
46d1c36833fd46ca88622272b3a12b72.fieldnorm
46d1c36833fd46ca88622272b3a12b72.idx
46d1c36833fd46ca88622272b3a12b72.pos
46d1c36833fd46ca88622272b3a12b72.posidx
46d1c36833fd46ca88622272b3a12b72.store
46d1c36833fd46ca88622272b3a12b72.term
47183260cd0c455ca05130a79c11c86b.fast
47183260cd0c455ca05130a79c11c86b.fieldnorm
47183260cd0c455ca05130a79c11c86b.idx
47183260cd0c455ca05130a79c11c86b.pos
47183260cd0c455ca05130a79c11c86b.posidx
47183260cd0c455ca05130a79c11c86b.store
47183260cd0c455ca05130a79c11c86b.term
4d178145571243608673580e0cdce10c.fast
4d178145571243608673580e0cdce10c.fieldnorm
4d178145571243608673580e0cdce10c.idx
4d178145571243608673580e0cdce10c.pos
4d178145571243608673580e0cdce10c.posidx
4d178145571243608673580e0cdce10c.store
4d178145571243608673580e0cdce10c.term
59aa70696b374354981875400b12c46e.fast
59aa70696b374354981875400b12c46e.fieldnorm
59aa70696b374354981875400b12c46e.idx
59aa70696b374354981875400b12c46e.pos
59aa70696b374354981875400b12c46e.posidx
59aa70696b374354981875400b12c46e.store
59aa70696b374354981875400b12c46e.term
6166244968ee4f208891a30c52fce997.fast
6166244968ee4f208891a30c52fce997.fieldnorm
6166244968ee4f208891a30c52fce997.idx
6166244968ee4f208891a30c52fce997.pos
6166244968ee4f208891a30c52fce997.posidx
6166244968ee4f208891a30c52fce997.store
6166244968ee4f208891a30c52fce997.term
6c48fffd8f754330b6631fdd433d6ec2.fast
6c48fffd8f754330b6631fdd433d6ec2.fieldnorm
6c48fffd8f754330b6631fdd433d6ec2.idx
6c48fffd8f754330b6631fdd433d6ec2.pos
6c48fffd8f754330b6631fdd433d6ec2.posidx
6c48fffd8f754330b6631fdd433d6ec2.store
6c48fffd8f754330b6631fdd433d6ec2.term
6f64907ac6d9499bb66b81201babd88a.fast
6f64907ac6d9499bb66b81201babd88a.fieldnorm
6f64907ac6d9499bb66b81201babd88a.idx
6f64907ac6d9499bb66b81201babd88a.pos
6f64907ac6d9499bb66b81201babd88a.posidx
6f64907ac6d9499bb66b81201babd88a.store
6f64907ac6d9499bb66b81201babd88a.term
758d63596b104705975aaf2d8de2da0c.fast
758d63596b104705975aaf2d8de2da0c.fieldnorm
758d63596b104705975aaf2d8de2da0c.idx
758d63596b104705975aaf2d8de2da0c.pos
758d63596b104705975aaf2d8de2da0c.posidx
758d63596b104705975aaf2d8de2da0c.store
758d63596b104705975aaf2d8de2da0c.term
79124a2b08af41089522a93474034c60.fast
79124a2b08af41089522a93474034c60.fieldnorm
79124a2b08af41089522a93474034c60.idx
79124a2b08af41089522a93474034c60.pos
79124a2b08af41089522a93474034c60.posidx
79124a2b08af41089522a93474034c60.store
79124a2b08af41089522a93474034c60.term
821159dea60347b7984cc52b2f6a938e.fast
821159dea60347b7984cc52b2f6a938e.fieldnorm
821159dea60347b7984cc52b2f6a938e.idx
821159dea60347b7984cc52b2f6a938e.pos
821159dea60347b7984cc52b2f6a938e.posidx
821159dea60347b7984cc52b2f6a938e.store
821159dea60347b7984cc52b2f6a938e.term
8d606d0d070b49048028a6c212c84ea8.fast
8d606d0d070b49048028a6c212c84ea8.fieldnorm
8d606d0d070b49048028a6c212c84ea8.idx
8d606d0d070b49048028a6c212c84ea8.pos
8d606d0d070b49048028a6c212c84ea8.posidx
8d606d0d070b49048028a6c212c84ea8.store
8d606d0d070b49048028a6c212c84ea8.term
999e64f80e514c4ba60ea23070ce1838.fast
999e64f80e514c4ba60ea23070ce1838.fieldnorm
999e64f80e514c4ba60ea23070ce1838.idx
999e64f80e514c4ba60ea23070ce1838.pos
999e64f80e514c4ba60ea23070ce1838.posidx
999e64f80e514c4ba60ea23070ce1838.store
999e64f80e514c4ba60ea23070ce1838.term
a676aa43aac54049be1dcfde3cf072ed.fast
a676aa43aac54049be1dcfde3cf072ed.fieldnorm
a676aa43aac54049be1dcfde3cf072ed.idx
a676aa43aac54049be1dcfde3cf072ed.pos
a676aa43aac54049be1dcfde3cf072ed.posidx
a676aa43aac54049be1dcfde3cf072ed.store
a676aa43aac54049be1dcfde3cf072ed.term
a7e307246f37421a9c775c04e9e4ec40.fast
a7e307246f37421a9c775c04e9e4ec40.fieldnorm
a7e307246f37421a9c775c04e9e4ec40.idx
a7e307246f37421a9c775c04e9e4ec40.pos
a7e307246f37421a9c775c04e9e4ec40.posidx
a7e307246f37421a9c775c04e9e4ec40.store
a7e307246f37421a9c775c04e9e4ec40.term
af3df244a6bd49479e328d05e3149428.fast
af3df244a6bd49479e328d05e3149428.fieldnorm
af3df244a6bd49479e328d05e3149428.idx
af3df244a6bd49479e328d05e3149428.pos
af3df244a6bd49479e328d05e3149428.posidx
af3df244a6bd49479e328d05e3149428.store
af3df244a6bd49479e328d05e3149428.term
b9df1958e53a41d38b7d305d38d812f0.fast
b9df1958e53a41d38b7d305d38d812f0.fieldnorm
b9df1958e53a41d38b7d305d38d812f0.idx
b9df1958e53a41d38b7d305d38d812f0.pos
b9df1958e53a41d38b7d305d38d812f0.posidx
b9df1958e53a41d38b7d305d38d812f0.store
b9df1958e53a41d38b7d305d38d812f0.term
bf31475c83b94241ac8a993ffdea6471.fast
bf31475c83b94241ac8a993ffdea6471.fieldnorm
bf31475c83b94241ac8a993ffdea6471.idx
bf31475c83b94241ac8a993ffdea6471.pos
bf31475c83b94241ac8a993ffdea6471.posidx
bf31475c83b94241ac8a993ffdea6471.store
bf31475c83b94241ac8a993ffdea6471.term
bf43c78f1c364f3a89b95dd497f21ceb.fast
bf43c78f1c364f3a89b95dd497f21ceb.fieldnorm
bf43c78f1c364f3a89b95dd497f21ceb.idx
bf43c78f1c364f3a89b95dd497f21ceb.pos
bf43c78f1c364f3a89b95dd497f21ceb.posidx
bf43c78f1c364f3a89b95dd497f21ceb.store
bf43c78f1c364f3a89b95dd497f21ceb.term
d5553d85e4984ca79890ac287b7d1f39.fast
d5553d85e4984ca79890ac287b7d1f39.fieldnorm
d5553d85e4984ca79890ac287b7d1f39.idx
d5553d85e4984ca79890ac287b7d1f39.pos
d5553d85e4984ca79890ac287b7d1f39.posidx
d5553d85e4984ca79890ac287b7d1f39.store
d5553d85e4984ca79890ac287b7d1f39.term
d88a890fde1445e6a0acd8b029d8d348.fast
d88a890fde1445e6a0acd8b029d8d348.fieldnorm
d88a890fde1445e6a0acd8b029d8d348.idx
d88a890fde1445e6a0acd8b029d8d348.pos
d88a890fde1445e6a0acd8b029d8d348.posidx
d88a890fde1445e6a0acd8b029d8d348.store
d88a890fde1445e6a0acd8b029d8d348.term
d8cc8fd8b60d477bbefa4a40c3ce13e5.fast
d8cc8fd8b60d477bbefa4a40c3ce13e5.fieldnorm
d8cc8fd8b60d477bbefa4a40c3ce13e5.idx
d8cc8fd8b60d477bbefa4a40c3ce13e5.pos
d8cc8fd8b60d477bbefa4a40c3ce13e5.posidx
d8cc8fd8b60d477bbefa4a40c3ce13e5.store
d8cc8fd8b60d477bbefa4a40c3ce13e5.term
eb332d5080234e979b29a01b6224715a.fast
eb332d5080234e979b29a01b6224715a.fieldnorm
eb332d5080234e979b29a01b6224715a.idx
eb332d5080234e979b29a01b6224715a.pos
eb332d5080234e979b29a01b6224715a.posidx
eb332d5080234e979b29a01b6224715a.store
eb332d5080234e979b29a01b6224715a.term
ee68835c830f4246a7deb1a01ba680ec.fast
ee68835c830f4246a7deb1a01ba680ec.fieldnorm
ee68835c830f4246a7deb1a01ba680ec.idx
ee68835c830f4246a7deb1a01ba680ec.pos
ee68835c830f4246a7deb1a01ba680ec.posidx
ee68835c830f4246a7deb1a01ba680ec.store
ee68835c830f4246a7deb1a01ba680ec.term
f37de432c03e4713b48d8347cc64a723.fast
f37de432c03e4713b48d8347cc64a723.fieldnorm
f37de432c03e4713b48d8347cc64a723.idx
f37de432c03e4713b48d8347cc64a723.pos
f37de432c03e4713b48d8347cc64a723.posidx
f37de432c03e4713b48d8347cc64a723.store
f37de432c03e4713b48d8347cc64a723.term
meta.json

meta.json:

`
{
  "segments": [
    {
      "segment_id": "01f94732-0247-4d2b-ab75-d0d6271f1b59",
      "max_doc": 18201,
      "deletes": null
    },
    {
      "segment_id": "47183260-cd0c-455c-a051-30a79c11c86b",
      "max_doc": 17898,
      "deletes": null
    },
    {
      "segment_id": "bf31475c-83b9-4241-ac8a-993ffdea6471",
      "max_doc": 16406,
      "deletes": null
    },
    {
      "segment_id": "022e975a-61eb-4a64-9d01-0d31d1afe322",
      "max_doc": 14951,
      "deletes": null
    },
    {
      "segment_id": "61662449-68ee-4f20-8891-a30c52fce997",
      "max_doc": 14928,
      "deletes": null
    },
    {
      "segment_id": "6f64907a-c6d9-499b-b66b-81201babd88a",
      "max_doc": 14144,
      "deletes": null
    },
    {
      "segment_id": "ee68835c-830f-4246-a7de-b1a01ba680ec",
      "max_doc": 13935,
      "deletes": null
    },
    {
      "segment_id": "3ef65b1c-1195-4fe3-8df8-4cfeea413cb0",
      "max_doc": 2163,
      "deletes": null
    },
    {
      "segment_id": "d5553d85-e498-4ca7-9890-ac287b7d1f39",
      "max_doc": 2148,
      "deletes": null
    },
    {
      "segment_id": "d88a890f-de14-45e6-a0ac-d8b029d8d348",
      "max_doc": 2124,
      "deletes": null
    },
    {
      "segment_id": "f37de432-c03e-4713-b48d-8347cc64a723",
      "max_doc": 2113,
      "deletes": null
    },
    {
      "segment_id": "a676aa43-aac5-4049-be1d-cfde3cf072ed",
      "max_doc": 2101,
      "deletes": null
    },
    {
      "segment_id": "123489ef-ac2c-4204-a856-fb44b1cc0c63",
      "max_doc": 2044,
      "deletes": null
    },
    {
      "segment_id": "3b57082d-d716-4be9-9717-762d61a3dbf9",
      "max_doc": 2043,
      "deletes": null
    },
    {
      "segment_id": "af3df244-a6bd-4947-9e32-8d05e3149428",
      "max_doc": 2038,
      "deletes": null
    },
    {
      "segment_id": "eb332d50-8023-4e97-9b29-a01b6224715a",
      "max_doc": 2012,
      "deletes": null
    },
    {
      "segment_id": "b9df1958-e53a-41d3-8b7d-305d38d812f0",
      "max_doc": 2003,
      "deletes": null
    },
    {
      "segment_id": "821159de-a603-47b7-984c-c52b2f6a938e",
      "max_doc": 2000,
      "deletes": null
    },
    {
      "segment_id": "59aa7069-6b37-4354-9818-75400b12c46e",
      "max_doc": 1998,
      "deletes": null
    },
    {
      "segment_id": "d8cc8fd8-b60d-477b-befa-4a40c3ce13e5",
      "max_doc": 1992,
      "deletes": null
    },
    {
      "segment_id": "22e58d87-d9cb-4eab-bc22-b7cf8e5ccc29",
      "max_doc": 1971,
      "deletes": null
    },
    {
      "segment_id": "79124a2b-08af-4108-9522-a93474034c60",
      "max_doc": 1911,
      "deletes": null
    },
    {
      "segment_id": "03d40ce6-be4f-4b84-ace2-9c82b979a3a4",
      "max_doc": 1910,
      "deletes": null
    },
    {
      "segment_id": "a7e30724-6f37-421a-9c77-5c04e9e4ec40",
      "max_doc": 1220,
      "deletes": null
    },
    {
      "segment_id": "999e64f8-0e51-4c4b-a60e-a23070ce1838",
      "max_doc": 1182,
      "deletes": null
    },
    {
      "segment_id": "6c48fffd-8f75-4330-b663-1fdd433d6ec2",
      "max_doc": 1098,
      "deletes": null
    },
    {
      "segment_id": "758d6359-6b10-4705-975a-af2d8de2da0c",
      "max_doc": 1093,
      "deletes": null
    },
    {
      "segment_id": "bf43c78f-1c36-4f3a-89b9-5dd497f21ceb",
      "max_doc": 1088,
      "deletes": null
    },
    {
      "segment_id": "4d178145-5712-4360-8673-580e0cdce10c",
      "max_doc": 1039,
      "deletes": null
    },
    {
      "segment_id": "0aca54b7-2f7a-4aba-af2d-6fa947009a8c",
      "max_doc": 1009,
      "deletes": null
    },
    {
      "segment_id": "8d606d0d-070b-4904-8028-a6c212c84ea8",
      "max_doc": 788,
      "deletes": null
    }
  ],
  "schema": [
    {
      "name": "thread_id",
      "type": "i64",
      "options": {
        "indexed": true,
        "stored": true
      }
    },
    {
      "name": "title",
      "type": "text",
      "options": {
        "indexing": {
          "record": "position",
          "tokenizer": "ru_stem"
        },
        "stored": true
      }
    },
    {
      "name": "text",
      "type": "text",
      "options": {
        "indexing": {
          "record": "position",
          "tokenizer": "ru_stem"
        },
        "stored": false
      }
    },
    {
      "name": "node_id",
      "type": "i64",
      "options": {
        "indexed": true,
        "stored": false
      }
    },
    {
      "name": "needModer",
      "type": "i64",
      "options": {
        "indexed": true,
        "stored": false
      }
    },
    {
      "name": "post_date",
      "type": "i64",
      "options": {
        "indexed": true,
        "stored": false
      }
    }
  ],
  "opstamp": 151637
}
`

List of files after my garbage_collect:

d04d0c8b05e34584bb6ee7551f0eb624.fast
d04d0c8b05e34584bb6ee7551f0eb624.fieldnorm
d04d0c8b05e34584bb6ee7551f0eb624.idx
d04d0c8b05e34584bb6ee7551f0eb624.pos
d04d0c8b05e34584bb6ee7551f0eb624.posidx
d04d0c8b05e34584bb6ee7551f0eb624.store
d04d0c8b05e34584bb6ee7551f0eb624.term
meta.json

**Comment by kkonevets** [comment] 2019-06-17 05:34
I should emphasize that first I delete all files and than call garbage_collect and index is still not empty as you can see. For example index/d04d0c8b05e34584bb6ee7551f0eb624.idx is 11Mb.

**Comment by fulmicoton** [comment] 2019-06-17 05:56
> "List of files after my garbage_collect"  

Do you really mean after calling your drop function ? or is it really just garbage collect ?
Calling garbage collect cannot do what you are decribing. Something else is happening that modified your meta.json file too.

**Comment by kkonevets** [comment] 2019-06-17 05:58
OK, I got it!

I have waited for 5 minutes after commit and then deleted files and then called `garbage_collect_files()`. And yes, the index directory became empty.

How can I wait for workers to finish merging segments without specifying `5 minutes` manually? Is there something like await possibility?

**Comment by fulmicoton** [comment] 2019-06-17 05:58
For the first set of files and... The discrepancy between meta.json and the list of segments is of 3 segment files. I'm going to bluntly assume that these are the result of segment merging, you just had to wait.

**Comment by fulmicoton** [comment] 2019-06-17 05:59
The issue is that you should not have to call `garbage_collect_files()` manually. My question is what happens if you do not call it.

**Comment by fulmicoton** [comment] 2019-06-17 06:00
`IndexWriter` has a `wait_merging_threads` method, but it consumes your index_writer instance.

**Comment by kkonevets** [comment] 2019-06-17 06:06
> My question is what happens if you do not call it.

If I wait for 5 minutes and do not call `garbage_collect_files()` manually it works correct.
But if I do not wait for 5 mins and do not call `garbage_collect_files()` manually index does not become empty.

So I guess I should call `wait_merging_threads` manually, I will try now

**Comment by fulmicoton** [comment] 2019-06-17 06:10
Ok, closing issue then.

The technique you used for clearing the index should be obsolete thanks to @petr-tik work. If you can work on master, you can try it. It should make your app much simpler and faster.

**Closed as completed by fulmicoton** 2019-06-17 06:10 UTC
Labels: bug

**Comment by kkonevets** [comment] 2019-06-17 06:13
Wait a minute, I used my own [technique](https://github.com/tantivy-search/tantivy/issues/510#issuecomment-495099648), what you mean by technique?

**Comment by fulmicoton** [comment] 2019-06-17 06:16
Yes. On the same ticket you linked, there is a link to a  PR from @petr-tik,

He added a `.delete_all_documents()` on the index writer. It should be much more efficient.
It is in master, and will be in 0.10 once released.

**Comment by kkonevets** [comment] 2019-06-17 07:32
Question regarded to `wait_merging_threads()`:
what am I supposed to do when I can't consume IndexWriter, like when using `Mutex<IndexWriter>`?
