### ISSUE TITLE
Document index file formats

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/tantivy#1002] opened 2021-03-30 21:08 UTC
We need to add a document which defines the different index file formats used in a given version of tantivy.

We can get some inspiration from [lucene old documentation page](https://lucene.apache.org/core/3_5_0/fileformats.html#Frequencies).

**Comment by fulmicoton** [comment] 2021-04-01 01:56
Closing as it is a duplicate of #981

**Closed as completed by fulmicoton** 2021-04-01 01:56 UTC
