### ISSUE TITLE
More Documents like this

### ISSUE THREAD

**Issue by syrusakbary** [quickwit-oss/tantivy#1011] opened 2021-04-17 00:11 UTC
It would be great to have a "MoreLikeThis" feature in Tantivy.
An efficient, effective "more-like-this" query generator would be a great contribution.

Elasticsearch and Lucene both support it:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html
https://lucene.apache.org/core/7_2_0/queries/org/apache/lucene/queries/mlt/MoreLikeThis.html

> Note: this came up when trying to add support for Tantivy in [Django-Haystack](https://django-haystack.readthedocs.io/en/master/backend_support.html#backend-support-matrix)

If it's helpful, here's how Whoosh (pure search engine implemented in Python) is doing it:
https://github.com/mchaput/whoosh/blob/main/src/whoosh/searching.py#L543-L585

**Comment by fulmicoton** [comment] 2021-04-27 07:28
Duplicate of #799

**Comment by mtlmacedo** [comment] 2023-03-16 00:41
Is this issue still open ?

**Comment by fulmicoton** [comment] 2023-03-16 01:38
ah no it has been implemented

**Closed as completed by fulmicoton** 2023-03-16 01:38 UTC
Labels: good first issue, high priority
